(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=(msg)=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)};
let mode='page', page=1, tracking=false, selectedBlock='title';
function setTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-tools').forEach(g=>g.classList.toggle('hidden',g.dataset.for!==name));}
$$('.tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
function setMode(next){mode=next;$('#pageMode').classList.toggle('active',mode==='page');$('#flowMode').classList.toggle('active',mode==='flow');$('#pageCanvas').style.display=mode==='page'?'block':'none';$('#flowCanvas').classList.toggle('active',mode==='flow');$('#modeStatus').textContent=mode==='page'?'Page Mode':'Flow Mode';$('.panel-tab[data-left="structure"]').click();if(mode==='page')$('.panel-tab[data-left="pages"]').click();toast(mode==='page'?'Page Mode — exact positioned page truth':'Flow Mode — semantic authoring state');}
$('#pageMode').addEventListener('click',()=>setMode('page'));$('#flowMode').addEventListener('click',()=>setMode('flow'));
function setPage(n){page=n;$$('[data-page-panel]').forEach(p=>p.classList.toggle('hidden',Number(p.dataset.pagePanel)!==n));$$('.thumb').forEach(t=>t.classList.toggle('active',Number(t.dataset.page)===n));if(n===2)setTimeout(showSelection,100);else $('#selectionFrame').style.display='none';}
$$('.thumb').forEach(t=>t.addEventListener('click',()=>{setMode('page');setPage(Number(t.dataset.page));}));
function showSelection(){const title=$('#selectableTitle'), frame=$('#selectionFrame'), pageEl=$('#articlePage');if(!title||pageEl.classList.contains('hidden'))return;const a=title.getBoundingClientRect(),b=pageEl.getBoundingClientRect();Object.assign(frame.style,{display:'block',left:(a.left-b.left-5)+'px',top:(a.top-b.top-5)+'px',width:(a.width+10)+'px',height:(a.height+10)+'px'});$('#objectType').textContent='Text frame';}
$('#selectableTitle').addEventListener('click',showSelection);window.addEventListener('resize',()=>{if(page===2&&mode==='page')showSelection()});
$$('.panel-tab[data-left]').forEach(b=>b.addEventListener('click',()=>{$$('.panel-tab[data-left]').forEach(x=>x.classList.toggle('active',x===b));$('#pagesPane').classList.toggle('hidden',b.dataset.left!=='pages');$('#structurePane').classList.toggle('hidden',b.dataset.left!=='structure');}));
$$('.panel-tab[data-right]').forEach(b=>b.addEventListener('click',()=>{$$('.panel-tab[data-right]').forEach(x=>x.classList.toggle('active',x===b));$('#formatPanel').classList.toggle('hidden',b.dataset.right!=='format');$('#reviewPanel').classList.toggle('hidden',b.dataset.right!=='review');$('#authorityPanel').classList.toggle('hidden',b.dataset.right!=='authority');}));
$$('.block').forEach(b=>b.addEventListener('click',()=>{$$('.block').forEach(x=>x.classList.toggle('selected',x===b));selectedBlock=b.dataset.block;$('#objectType').textContent='Semantic block';}));
$('#commentBtn').addEventListener('click',()=>{$('.panel-tab[data-right="review"]').click();toast('Review panel opened — comments stay separate from source authority.');});
$('#addComment').addEventListener('click',()=>{const p=document.createElement('div');p.className='comment';p.innerHTML='<strong>You · demo</strong><p>New review note staged in collaboration metadata.</p>';$('#addComment').before(p);toast('Review note added to demo collaboration layer.');});
$('#trackBtn').addEventListener('click',()=>{tracking=!tracking;const t=$('#trackedText');t.classList.toggle('tracked-insert',tracking);if(mode==='flow'){$('.block[data-block="p2"] p').classList.toggle('tracked-insert',tracking)};toast(tracking?'Track Changes ON — insertion marked':'Track Changes OFF');});
$('#historyBtn').addEventListener('click',()=>$('#historyPanel').classList.toggle('open'));$('#closeHistory').addEventListener('click',()=>$('#historyPanel').classList.remove('open'));
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBg').classList.add('open');}
function closeModal(){$('#modalBg').classList.remove('open')}$('#modalClose').addEventListener('click',closeModal);$('#modalDone').addEventListener('click',closeModal);$('#modalBg').addEventListener('click',e=>{if(e.target.id==='modalBg')closeModal()});
$('#preflightBtn').addEventListener('click',()=>openModal('Press Preflight',`<div class="proof-grid"><div class="proof-item"><strong class="pass">PASS · Source identity</strong><small>Frozen PDF hash retained</small></div><div class="proof-item"><strong class="pass">PASS · Font evidence</strong><small>Subset / embedding state visible</small></div><div class="proof-item"><strong class="pass">PASS · Page boxes</strong><small>Media / Crop / Trim / Bleed inspected</small></div><div class="proof-item"><strong class="pass">PASS · Images</strong><small>Effective DPI evidence available</small></div><div class="proof-item"><strong class="hold">UNKNOWN · PDF/X certification</strong><small>Not silently promoted</small></div><div class="proof-item"><strong class="hold">UNKNOWN · Output profile</strong><small>Evidence only in this public demo</small></div></div>`));
$('#proofBtn').addEventListener('click',()=>openModal('Proof State',`<div class="proof-grid"><div class="proof-item"><strong class="pass">G1–G5I · controlled PASS</strong><small>42/42 current regression tests in the reference build</small></div><div class="proof-item"><strong class="pass">Authority model</strong><small>PDF, DOCX, Flow, Page deltas and assets kept distinct</small></div><div class="proof-item"><strong class="hold">Browser runtime</strong><small>Public-demo runtime is proven separately from engineering proof</small></div><div class="proof-item"><strong class="hold">External cloud HA</strong><small>Not implied by the reference provider</small></div></div><p style="font-size:10px;line-height:1.55;color:#61675e;margin:14px 0 0">This public interface demonstrates Publisher Studio’s interaction model and product direction. Engineering claims remain bounded to the controlled evidence carried by the G5I reference build.</p>`));
$('#exportBtn').addEventListener('click',()=>openModal('Export',`<div class="proof-grid"><div class="proof-item"><strong>PDF</strong><small>Page or semantic export with proof receipt</small></div><div class="proof-item"><strong>DOCX</strong><small>Supported semantic Word subset</small></div><div class="proof-item"><strong>.psproj</strong><small>Hash-verified project authority envelope</small></div><div class="proof-item"><strong>.psstate</strong><small>Portable application state backup</small></div></div>`));
$('#undo').addEventListener('click',()=>toast('Undo is reversible in the production kernel; this public demo keeps interaction local.'));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('#historyPanel').classList.remove('open')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();toast('Find · search is available in the production reader core.')}});
setPage(1);
})();
